name: Setup properties
description: Add URL properties to local.properties

runs:
  using: composite
  steps:
    - name: Add properties to local.properties
      shell: bash
      run: |
        echo "INSTAGRAM_URL=${{ vars.INSTAGRAM_URL }}" >> local.properties
        echo "YOUTUBE_URL=${{ vars.YOUTUBE_URL }}" >> local.properties
        echo "TIKTOK_URL=${{ vars.TIKTOK_URL }}" >> local.properties
        echo "STORAGE_URL=${{ vars.STORAGE_URL }}" >> local.properties
        echo "DATABASE_URL_HOST=${{ vars.DATABASE_URL_HOST }}" >> local.properties
