[versions]
androidx-lifecycle = "2.9.6"
compose-multiplatform = "1.10.0-beta01"
compose-hot-reload="1.0.0-rc03"
kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
kotlinx-serialization = "1.9.0"
ksp = "2.2.21-2.0.4"
tiamat = "2.1.0"
koin-version = "4.1.1"
koin-annotations = "2.3.1"
flowmvi = "3.2.1"
ktor = "3.3.2"
datastore = "1.2.0"
kotlin-browser = "0.4"
gradle-versions = "0.53.0"
buildkonfig = "0.17.1"
mockk = "1.14.6"
coil = "3.3.0"

[libraries]
# Kotlin
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlin-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlin-browser" }

# Testing
mockk-core = { module = "io.mockk:mockk", version.ref = "mockk" }

# AndroidX Compose & Lifecycle
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }


# Compose Material
material3-windowsize = "org.jetbrains.compose.material3:material3-window-size-class:1.8.2"
compose-ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "compose-multiplatform" }

# Datastore
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-datastore-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }

# Dependencies for build-logic module
compose-compiler-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

#Koin - using explicit versions for multiplatform compatibility
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-version" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-version" }
koin-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin-version" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }

# Koin testing
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin-version" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin-version" }

#Tiamat
tiamat = { module = "io.github.composegears:tiamat", version.ref = "tiamat" }

# FlowMVI
flowmvi-core = { module = "pro.respawn.flowmvi:core", version.ref = "flowmvi" }
flowmvi-test = { module = "pro.respawn.flowmvi:test", version.ref = "flowmvi" }
flowmvi-compose = { module = "pro.respawn.flowmvi:compose", version.ref = "flowmvi" }
flowmvi-savedstate = { module = "pro.respawn.flowmvi:savedstate", version.ref = "flowmvi" }

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Coil
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

[plugins]
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.6" }
google-services = { id = "com.google.gms.google-services", version = "4.4.4" }
jetbrains-compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hot-reload"}

kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version = "2.0.1" }
gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }

# Project conventional plugins
hannasequestrianproject-kmp-compose = { id = "hannasequestrianproject.kmp.compose" }
hannasequestrianproject-kmp-library = { id = "hannasequestrianproject.kmp.library" }
